# Generated by Django 5.1.2 on 2024-12-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_api', '0003_alter_workschedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='date',
            field=models.DateField(default='2024-10-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
