# Generated by Django 5.1.2 on 2024-12-26 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0002_alter_booking_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='planned_begin_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='planned_end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
